#!/bin/bash

DOTFILES=$(pwd)
CONFIG=${CONFIG:-$HOME/.config}

setup_xcode() {
	xcode-select --install || true
}

setup_homebrew() {
	command -v brew &>/dev/null || /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)";
	brew update
	brew upgrade
	brew bundle --file=$DOTFILES/Brewfile
}

setup_symlinks() {
	if ! test -d $CONFIG/fish; ln -s $DOTFILES/files/fish $CONFIG/fish; end
	if ! test -d $HOME/.hammerspoon; ln -s $DOTFILES/files/hammerspoon $HOME/.hammerspoon; end
	if ! test -d $CONFIG/tmux; ln -s $DOTFILES/files/tmux $CONFIG/tmux; end
	if ! test -d $CONFIG/nvim; ln -s $DOTFILES/files/nvim $CONFIG/nvim; end
	if ! test -d $CONFIG/git; ln -s $DOTFILES/files/git $CONFIG/git; end
	if ! test -d $CONFIG/gh; ln -s $DOTFILES/files/gh $CONFIG/gh; end
	if ! test -d $CONFIG/kitty; ln -s $DOTFILES/files/kitty $CONFIG/kitty; end
	if ! test -d $CONFIG/starship; ln -s $DOTFILES/files/starship $CONFIG/starship; end
}

setup_mac_defaults() {
	source ./scripts/mac-defaults.sh
}

main() {
  echo "CONFIG: $CONFIG"
  echo "DOTFILES: $DOTFILES"
  echo ""

  echo "Setting up XCode..."
  setup_xcode
  echo "XCode setup"

  echo "Setting up Homebrew..."
  setup_brew
  echo "Homebrew setup"

  echo "Setting up Symlinks..."
  setup_symlinks
  echo "Symlinks setup"

  echo "Setting up Mac Defaults..."
  setup_mac_defaults
  echo "Mac Defaults setup"
}

main

