"$schema" = 'https://starship.rs/config-schema.json'

palette = 'rygar'
add_newline = false

#    
#  
#  
#  󰌾
# 󰬃 󰫿 󰫻
#     󱡋

format = """
$jobs\
[](fg:grad_1)\
$directory\
[ ](fg:grad_1 bg:grad_2)\
$git_branch\
$git_commit\
$git_state\
$git_status\
[ ](fg:grad_2 bg:grad_4)\
$bun\
$nodejs\
$rust\
$python\
$c\
$golang\
$gradle\
[](fg:grad_4)\
\n\

$character\
"""

[custom.gitproject]
command = "basename $(dirname $(git rev-parse --git-common-dir))"
format = '[ $symbol $output ]($style)'
style = 'fg:white bg:grad_1'
when = ''' [ "$(git rev-parse --git-dir 2>/dev/null)" != "$(git rev-parse --git-common-dir 2>/dev/null)" ] '''
shell = ['bash', '--noprofile', '-norc']
disabled = false

[custom.directory]
command = '''
echo $PWD
'''
format = '[ $symbol $output ]($style)'
symbol = ''
style = 'fg:white bg:grad_1'
when = ''' [ "$(git rev-parse --git-dir 2>/dev/null)" == "$(git rev-parse --git-common-dir 2>/dev/null)" ] '''
shell = ['bash', '--noprofile', '-norc']
disabled = false

[directory]
style = "fg:white bg:grad_1"
repo_root_style = "fg:white bg:grad_1"
format = "[  $path$read_only ]($style)"
repo_root_format = "[  $repo_root$read_only$path ]($style)"
truncation_symbol = "…/"
truncation_length = 4
fish_style_pwd_dir_length = 2
truncate_to_repo = false
home_symbol = "~"
read_only = "(󰌾)"

[directory.substitutions]
"~/code/github.com/rjschie" = "~mygh"
"~/code/github.com" = "~gh"

[jobs]
format = '[$symbol$number]($style)'
style = 'fg:grad_7'

[git_branch]
symbol = " "
format = "[$symbol$branch(:$remote_branch) ]($style)"
only_attached = true
style = "fg:white bg:grad_2"

[git_commit]
format = '[ $hash$tag ]($style)'
tag_symbol = '  '
style = 'fg:white bg:grad_2'

[git_status]
format = '[$all_status$ahead_behind ]($style)'
style = 'fg:white bg:grad_2'

[character]
format = '$symbol'
success_symbol = '[-](fg:grad_1)[|](fg:grad_5)[  ](fg:grad_7)'
error_symbol = '[-](fg:grad_1)[|](fg:grad_5)[  ](fg:grad_red)'
vimcmd_symbol = '[ ](fg:grad_1)[󰫻 ](fg:grad_7)[| ](fg:grad_7)'
vimcmd_replace_one_symbol = '[ ](fg:grad_1)[󰫿 ](fg:grad_orange)[| ](fg:grad_7)'
vimcmd_replace_symbol = '[ ](fg:grad_1)[󰫿+](fg:grad_orange)[| ](fg:grad_7)'
vimcmd_visual_symbol = '[ ](fg:grad_1)[󰬃 ](fg:grad_4)[| ](fg:grad_7)'

[bun]
symbol = '󱡋 '
format = '[$symbol($version) ]($style)'
style = 'fg:white bg:grad_4'
[c]
symbol = " "
style = 'fg:white bg:grad_4'
format = "[$symbol($version )]($style)"
[golang]
symbol = " "
style = 'fg:white bg:grad_4'
format = "[$symbol($version )]($style)"
[lua]
symbol = " "
style = 'fg:white bg:grad_4'
format = "[$symbol($version )]($style)"
[nodejs]
symbol = " "
style = 'fg:white bg:grad_4'
format = "[$symbol($version )]($style)"
[python]
disabled = true
symbol = " "
style = 'fg:white bg:grad_4'
format = "[${symbol}${pyenv_prefix}(${version} )(\\(${virtualenv}\\) )]($style)"
version_format = 'v${major}.${minor}'
[rust]
symbol = " "
style = 'fg:white bg:grad_4'
format = "[$symbol($version )]($style)"
[zig]
symbol = " "
style = 'fg:white bg:grad_4'
format = "[$symbol($version )]($style)"

[palettes.rygar]
white = '#ffffff'
grad_1 = '#e42dc0'
grad_2 = '#bd4bcb'
grad_3 = '#9b65d4'
grad_4 = '#7483df'
grad_5 = '#509fe9'
grad_6 = '#27bff4'
grad_7 = '#00ddff'
grad_red = '#e73155'
grad_cyan = '#06ecf8'
grad_magenta = '#f913a9'
grad_green = '#06f8a6'
grad_orange = '#f8b606'
